Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.box_architecture = "arm64"
  config.vm.provider "vmware_desktop" do |vmware|
    vmware.gui = true
    vmware.cpus = 2
    vmware.vmx["ethernet0.virtualdev"] = "vmxnet3"
    vmware.ssh_info_public = true
    vmware.linked_clone = false
  end
  config.vm.provision "shell", inline: <<-SHELL
  sudo apt update
  sudo apt install -y python3
  sudo apt install -y python3-pip
  sudo apt install -y python*-psycopg2
  sudo apt install -y python*-django
  SHELL
  config.vm.provision "file", source: "./testfile", destination: "testfile"
end